"""Build the RSS podcast feed.xml from R2 episode list.

Two feeds are generated by the pipeline:
- ``feed.xml`` (full)    — all sections, private listening.
- ``feed-general.xml``   — public/sharing version, fewer sections.

Each feed has its own template, title, description and author, controlled
via env vars (``PODCAST_*`` for full, ``PODCAST_*_GENERAL`` for general).
"""
from __future__ import annotations

import os
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path

from jinja2 import Template

_EDITORIAL_BLOCK = (
    "Revue quotidienne d'actualités générales et scientifiques de six à huit minutes.\n"
    "Ligne éditoriale : loin de la culture du clic qui polarise les débats et du flux "
    "d'informations constamment négatives qui assombrit notre vision du monde, cette "
    "revue offre un contenu factuel, forcément moins spectaculaire, mais plus "
    "constructif, équilibré et apaisant pour démarrer la journée.\n"
    "Actualités générales : L'essentiel de l'actualité (Monde, Suisse, Vaud, Lausanne) "
    "sourcé exclusivement auprès de médias de référence (RTS, Le Temps, 24 heures, "
    "Tribune de Genève, Swissinfo, Le Monde, Reuters, AFP).\n"
)
_DEFAULT_DESCRIPTION_FULL = (
    _EDITORIAL_BLOCK
    + "Actualités scientifiques : 1 à 2 études portant sur la recherche générale "
    "(issues du Big 5 : Nature, Science, Cell, The Lancet, NEJM), l'hypoxie clinique "
    "et appliquée, les sciences du sport et l'IA en santé."
)
_DEFAULT_DESCRIPTION_GENERAL = (
    _EDITORIAL_BLOCK
    + "Actualités scientifiques : 1 à 2 études portant sur la recherche générale "
    "(issues du Big 5 : Nature, Science, Cell, The Lancet, NEJM) et les sciences du sport."
)

# Feed configuration: variant name -> (template filename, env-var prefix, default title/description/filename).
_FEED_PROFILES: dict[str, dict] = {
    "full": {
        "template": "feed_template.xml",
        "title_env": "PODCAST_TITLE",
        "title_default": "Revue quotidienne",
        "description_env": "PODCAST_DESCRIPTION",
        "description_default": _DEFAULT_DESCRIPTION_FULL,
        "author_env": "PODCAST_AUTHOR",
        "author_default": "Tom",
        "filename_env": "FEED_FILENAME",
        "filename_default": "feed.xml",
    },
    "general": {
        "template": "feed_template_general.xml",
        "title_env": "PODCAST_TITLE_GENERAL",
        "title_default": "Revue du jour",
        "description_env": "PODCAST_DESCRIPTION_GENERAL",
        "description_default": _DEFAULT_DESCRIPTION_GENERAL,
        "author_env": "PODCAST_AUTHOR_GENERAL",
        "author_default": "Tom",
        "filename_env": "FEED_FILENAME_GENERAL",
        "filename_default": "feed-general.xml",
    },
}


def feed_filename(variant: str = "full") -> str:
    """Return the filename to use for the given feed variant (e.g. ``feed.xml``)."""
    profile = _FEED_PROFILES[variant]
    return os.environ.get(profile["filename_env"], profile["filename_default"])


def render_feed(episodes: list[dict], cover_url: str, *, variant: str = "full") -> str:
    """Render an RSS feed for the given variant (``full`` or ``general``).

    ``episodes`` is a list of dicts produced by :func:`build_episode_entry`.
    ``cover_url`` is the public URL of the cover image (shared by both feeds).
    """
    if variant not in _FEED_PROFILES:
        raise ValueError(f"Unknown feed variant: {variant!r}. Expected one of {list(_FEED_PROFILES)}.")
    profile = _FEED_PROFILES[variant]

    tpl_path = Path(__file__).resolve().parent.parent / "assets" / profile["template"]
    tpl = Template(tpl_path.read_text(encoding="utf-8"))

    return tpl.render(
        title=os.environ.get(profile["title_env"], profile["title_default"]),
        description=os.environ.get(profile["description_env"], profile["description_default"]),
        author=os.environ.get(profile["author_env"], profile["author_default"]),
        email=os.environ.get("PODCAST_EMAIL", ""),
        language=os.environ.get("PODCAST_LANGUAGE", "fr-FR"),
        cover_url=cover_url,
        site_url=os.environ.get("R2_PUBLIC_URL", "").rstrip("/"),
        feed_filename=feed_filename(variant),
        last_build_date=format_datetime(datetime.now(timezone.utc)),
        episodes=episodes,
    )


def build_episode_entry(*, url: str, date: datetime, size: int,
                        title: str, description: str, duration_seconds: int) -> dict:
    return {
        "url": url,
        "size": size,
        "title": title,
        "description": description,
        "pub_date": format_datetime(date),
        "guid": url,
        "duration": _format_duration(duration_seconds),
    }


def _format_duration(seconds: int) -> str:
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"
